"""Phase 2A — DFX Insight Engine (deterministic, backend-owned).

Turns the SAME authoritative report aggregates the Reports page already shows
into concise business/scheme insights and prioritised recommendations. There is
NO external AI/LLM dependency — every sentence is generated by fixed rules over
real figures.

Guarantees:
  * No number is fabricated. Every figure comes from ReportService /
    TopProductsService (backend is the source of truth). Nothing is invented,
    and missing values are never shown as ₹0 — they are reported as unavailable
    or simply omitted.
  * Only period-over-period comparisons the data supports are stated; when the
    previous period has no comparable base, the trend is reported without a %.
  * Tenant isolation is inherited: every underlying service call is
    tenant-scoped via the authenticated user.
  * Profit is only ever surfaced for privileged (Admin/SuperAdmin) users.
  * Insufficient data yields available=False with an "Insufficient data" note,
    never a manufactured analysis.
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import List, Optional, Tuple

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.auth import User
from app.schemas.report import (
    AiAnalysisResponse,
    AiRecommendedAction,
    DateRangeInfo,
)
from app.services.billing_service import _is_privileged
from app.services.report_service import (
    ReportService,
    TopProductsService,
    _resolve_range,
    _previous_range,
    _growth_percent,
)

_TOP_N = 8
_ENGINE = "DFX Insight Engine"


def _inr(v: float) -> str:
    return f"₹{v:,.0f}"


def _pct(v: float) -> str:
    return f"{abs(v):.1f}%"


def _dir(v: float) -> str:
    return "increased" if v >= 0 else "decreased"


class AiAnalystService:
    @staticmethod
    async def analyze(
        db: AsyncSession,
        current_user: User,
        domain: str,
        period: Optional[str],
        date_from: Optional[date],
        date_to: Optional[date],
    ) -> AiAnalysisResponse:
        ReportService._require_tenant(current_user)  # tenant guard (raises if none)
        if domain == "BUSINESS":
            return await AiAnalystService._business(db, current_user, period, date_from, date_to)
        return await AiAnalystService._scheme(db, current_user, period, date_from, date_to)

    # ── BUSINESS ────────────────────────────────────────────────────────────

    @staticmethod
    async def _business(db, user, period, date_from, date_to) -> AiAnalysisResponse:
        privileged = _is_privileged(user)
        d_from, d_to, _ = _resolve_range(period, date_from, date_to)
        prev_from, prev_to = _previous_range(d_from, d_to)

        trend = await ReportService.get_sales_trend(db, user, period, date_from, date_to)
        rng = trend.range
        prev = await ReportService.get_sales_trend(db, user, None, prev_from, prev_to)
        category = await ReportService.get_sales_by_category(db, user, period, date_from, date_to)
        top_products = await TopProductsService.get_top_products(
            db, user, d_from, d_to, "revenue", _TOP_N
        )
        top_customers = await ReportService.get_top_customers_by_sales(
            db, user, period, date_from, date_to, _TOP_N
        )

        cur_rev = round(sum(p.total_amount for p in trend.trend), 2)
        cur_cnt = sum(p.sale_count for p in trend.trend)
        cur_gold = round(sum(p.gold_weight_grams for p in trend.trend), 3)
        cur_profit = round(sum(p.profit for p in trend.trend), 2) if privileged else None
        prev_rev = round(sum(p.total_amount for p in prev.trend), 2)
        prev_cnt = sum(p.sale_count for p in prev.trend)
        prev_profit = round(sum(p.profit for p in prev.trend), 2) if privileged else None

        if cur_cnt == 0:
            return AiAnalystService._empty("BUSINESS", rng, "No completed sales in this period.")

        rev_growth = _growth_percent(cur_rev, prev_rev)
        cnt_growth = _growth_percent(cur_cnt, prev_cnt)
        profit_growth = _growth_percent(cur_profit, prev_profit) if privileged else None

        findings: List[str] = []
        opportunities: List[str] = []
        risks: List[str] = []
        actions: List[AiRecommendedAction] = []

        # Revenue trend
        if rev_growth is not None:
            findings.append(
                f"Revenue {_dir(rev_growth)} {_pct(rev_growth)} versus the previous period "
                f"({_inr(prev_rev)} → {_inr(cur_rev)})."
            )
        else:
            findings.append(f"Revenue was {_inr(cur_rev)} across {cur_cnt} sale(s); no comparable previous period.")

        # Profit trend (privileged only)
        if privileged and cur_profit is not None:
            if profit_growth is not None:
                findings.append(f"Profit {_dir(profit_growth)} {_pct(profit_growth)} ({_inr(prev_profit)} → {_inr(cur_profit)}).")
            else:
                findings.append(f"Profit was {_inr(cur_profit)} for this period.")

        # Category strength / weakness
        cats = sorted(category.categories, key=lambda c: c.total_sales, reverse=True)
        if cats:
            top_cat = cats[0]
            findings.append(
                f"{top_cat.category or 'Uncategorised'} is the strongest category by revenue "
                f"({_inr(top_cat.total_sales)}, {top_cat.percentage:.1f}% of sales)."
            )
            opportunities.append(f"Maintain stock and promotion for {top_cat.category or 'the top category'}.")
            actions.append(AiRecommendedAction(
                priority="MEDIUM",
                title=f"Prioritise {top_cat.category or 'the top category'}",
                explanation="Strongest revenue contributor this period — protect stock and keep it promoted.",
                metric=f"{_inr(top_cat.total_sales)} ({top_cat.percentage:.1f}%)",
            ))
            if len(cats) > 1:
                weak = cats[-1]
                findings.append(
                    f"{weak.category or 'Uncategorised'} is the weakest category by revenue "
                    f"({_inr(weak.total_sales)}, {weak.percentage:.1f}%)."
                )
                risks.append(f"{weak.category or 'One category'} contributes only {weak.percentage:.1f}% of sales.")
                actions.append(AiRecommendedAction(
                    priority="LOW",
                    title=f"Review {weak.category or 'the weakest category'}",
                    explanation="Lowest revenue share — review pricing, stock mix or promotion.",
                    metric=f"{_inr(weak.total_sales)} ({weak.percentage:.1f}%)",
                ))

        # Top product + high-value pattern
        items = top_products["items"]
        if items:
            tp = items[0]
            findings.append(f"{tp['product_name']} led sales with {tp['units']} unit(s) and {_inr(tp['revenue'])} revenue.")
            hv = next(
                (it for it in items if it["units"] > 0 and it["revenue"] / it["units"] >= (cur_rev / cur_cnt) * 1.5),
                None,
            )
            if hv and hv["units"] <= max(2, cur_cnt // 20):
                findings.append(
                    f"{hv['product_name']} shows high revenue on low volume "
                    f"({hv['units']} unit(s), {_inr(hv['revenue'])}) — high-value sales."
                )
                opportunities.append(f"Promote high-value line {hv['product_name']}.")

        # Volume vs revenue divergence
        if rev_growth is not None and cnt_growth is not None:
            if rev_growth >= 0 and cnt_growth < 0:
                findings.append(f"Revenue rose ({_pct(rev_growth)}) while sales volume fell ({_pct(cnt_growth)}) — higher-value mix.")
            elif rev_growth < 0 and cnt_growth >= 0:
                findings.append(f"Sales volume rose ({_pct(cnt_growth)}) but revenue fell ({_pct(rev_growth)}) — lower-value mix.")
                risks.append("Revenue is falling despite steady volume — check discounting or product mix.")

        # Declines → HIGH priority actions
        if rev_growth is not None and rev_growth < 0:
            risks.append(f"Revenue declined {_pct(rev_growth)} versus the previous period.")
            actions.insert(0, AiRecommendedAction(
                priority="HIGH",
                title="Address the revenue decline",
                explanation="Revenue fell versus the previous period — review demand, pricing and top-category stock.",
                metric=f"{_inr(prev_rev)} → {_inr(cur_rev)} ({_pct(rev_growth)} down)",
            ))
        if privileged and profit_growth is not None and profit_growth < 0:
            risks.append(f"Profit declined {_pct(profit_growth)} versus the previous period.")
            actions.insert(0, AiRecommendedAction(
                priority="HIGH",
                title="Investigate the profit drop",
                explanation="Profit fell versus the previous period — review margins and purchase costs.",
                metric=f"{_inr(prev_profit)} → {_inr(cur_profit)} ({_pct(profit_growth)} down)",
            ))

        AiAnalystService._birthday_notes(
            await ReportService.get_birthday_summary(db, user, "BUSINESS", period, date_from, date_to),
            "business", findings, opportunities, actions,
        )

        summary = AiAnalystService._summary_line(
            "Business", rng.label, cur_rev, rev_growth, cur_cnt,
            gold=cur_gold, profit=cur_profit if privileged else None,
        )

        return AiAnalystService._build("BUSINESS", rng, summary, findings, opportunities, risks, actions)

    # ── SCHEME ──────────────────────────────────────────────────────────────

    @staticmethod
    async def _scheme(db, user, period, date_from, date_to) -> AiAnalysisResponse:
        payments = await ReportService.get_payment_summary(db, user, period, date_from, date_to)
        enrollments = await ReportService.get_enrollment_summary(db, user, period, date_from, date_to)
        schemes = await ReportService.get_scheme_summary(db, user, period, date_from, date_to)
        top_customers = await ReportService.get_top_customers(db, user, period, date_from, date_to, _TOP_N)
        rng = payments.range

        if payments.success_payment_count == 0 and enrollments.new_enrollments_in_range == 0 and enrollments.active_count == 0:
            return AiAnalystService._empty("SCHEME", rng, "No scheme collections or enrollments in this period.")

        findings: List[str] = []
        opportunities: List[str] = []
        risks: List[str] = []
        actions: List[AiRecommendedAction] = []

        cg = payments.total_revenue_growth_percent
        if cg is not None:
            findings.append(f"Scheme collections {_dir(cg)} {_pct(cg)} to {_inr(payments.total_revenue)} this period.")
        else:
            findings.append(f"Scheme collections were {_inr(payments.total_revenue)} this period.")

        # Outstanding dues → follow-up
        if payments.outstanding_dues > 0:
            og = payments.outstanding_dues_growth_percent
            tail = f" ({_dir(og)} {_pct(og)})" if og is not None else ""
            findings.append(f"Outstanding dues stand at {_inr(payments.outstanding_dues)}{tail}.")
            actions.append(AiRecommendedAction(
                priority="HIGH",
                title="Follow up on outstanding dues",
                explanation="Pending installments are outstanding — prioritise collection follow-up.",
                metric=_inr(payments.outstanding_dues),
            ))
            risks.append(f"{_inr(payments.outstanding_dues)} in dues is outstanding.")

        # Enrollment activity
        findings.append(
            f"{enrollments.active_count} active passbook(s); {enrollments.new_enrollments_in_range} new this period, "
            f"{enrollments.completed_count} completed, {enrollments.cancelled_count} cancelled."
        )
        if enrollments.retention_rate_percent is not None:
            findings.append(f"Scheme retention is {enrollments.retention_rate_percent:.1f}%.")

        # Scheme performance
        by_collected = sorted(schemes.schemes, key=lambda s: s.total_collected, reverse=True)
        by_active = sorted(schemes.schemes, key=lambda s: s.active_enrollments, reverse=True)
        if by_collected:
            best = by_collected[0]
            findings.append(f"{best.scheme_name} leads collections ({_inr(best.total_collected)}, {best.active_enrollments} active).")
            opportunities.append(f"Build on {best.scheme_name}'s strong collection performance.")
            actions.append(AiRecommendedAction(
                priority="MEDIUM",
                title=f"Focus on {best.scheme_name}",
                explanation="Highest collections — strong candidate for enrollment drives.",
                metric=_inr(best.total_collected),
            ))
            if by_active and by_active[0].scheme_id != best.scheme_id:
                findings.append(f"{by_active[0].scheme_name} has the most active enrollments ({by_active[0].active_enrollments}).")
            active_schemes = [s for s in by_collected if s.is_active]
            if len(active_schemes) > 1:
                weak = active_schemes[-1]
                findings.append(f"{weak.scheme_name} has the weakest collections among active schemes ({_inr(weak.total_collected)}).")
                risks.append(f"{weak.scheme_name} is underperforming on collections.")
                actions.append(AiRecommendedAction(
                    priority="LOW",
                    title=f"Review {weak.scheme_name}",
                    explanation="Weakest active-scheme collections — review enrollment and follow-up.",
                    metric=_inr(weak.total_collected),
                ))

        # High-value customers
        if top_customers.customers:
            hc = top_customers.customers[0]
            findings.append(f"{hc.customer_name} is the highest-value customer ({_inr(hc.total_invested)} invested).")
            opportunities.append("Recognise and retain high-value scheme customers.")

        # Collections decline → HIGH
        if cg is not None and cg < 0:
            actions.insert(0, AiRecommendedAction(
                priority="HIGH",
                title="Reverse the collections decline",
                explanation="Scheme collections fell versus the previous period — intensify installment follow-up.",
                metric=f"{_pct(cg)} down",
            ))

        AiAnalystService._birthday_notes(
            await ReportService.get_birthday_summary(db, user, "SCHEME", period, date_from, date_to),
            "scheme", findings, opportunities, actions,
        )

        summary = AiAnalystService._summary_line(
            "Scheme", rng.label, payments.total_revenue, cg, enrollments.active_count,
            outstanding=payments.outstanding_dues,
        )

        return AiAnalystService._build("SCHEME", rng, summary, findings, opportunities, risks, actions)

    # ── shared builders ──────────────────────────────────────────────────────

    @staticmethod
    def _summary_line(kind, label, revenue, growth, count, gold=None, profit=None, outstanding=None) -> str:
        head = "collections" if kind == "Scheme" else "revenue"
        s = f"{kind} {head} for {label}: {_inr(revenue)}"
        if growth is not None:
            s += f" ({_dir(growth)} {_pct(growth)})"
        if kind == "Business":
            s += f", {count} sale(s)"
            if gold:
                s += f", {gold:.3f} g gold sold"
            if profit is not None:
                s += f", profit {_inr(profit)}"
        else:
            s += f", {count} active passbook(s)"
            if outstanding:
                s += f", {_inr(outstanding)} outstanding"
        return s + "."

    @staticmethod
    def _birthday_notes(bday, kind: str, findings, opportunities, actions) -> None:
        """Fold real birthday-opportunity facts into the insight lists. Counts
        only — no fabricated benefit, no invented eligibility."""
        today_pri = sum(1 for c in bday.today if c.is_priority)
        if today_pri:
            findings.append(f"{today_pri} high-value {kind} customer(s) have a birthday today.")
        if bday.priority_count:
            findings.append(
                f"{bday.priority_count} high-value {kind} customer(s) have a birthday within {bday.window_days} days."
            )
            opportunities.append(
                f"Contact priority birthday customers before their birthday and consider a complimentary gesture."
            )
            actions.append(AiRecommendedAction(
                priority="HIGH" if today_pri else "MEDIUM",
                title="Reach out to priority birthday customers",
                explanation="High-value customers with an imminent birthday — a timely relationship touchpoint.",
                metric=f"{bday.priority_count} within {bday.window_days} days",
            ))
        elif (bday.today_count + bday.upcoming_count) > 0:
            opportunities.append(
                f"{bday.today_count + bday.upcoming_count} customer birthday(s) within {bday.window_days} days — an outreach opportunity."
            )

    @staticmethod
    def _build(domain, rng, summary, findings, opportunities, risks, actions) -> AiAnalysisResponse:
        rank = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        actions = sorted(actions, key=lambda a: rank[a.priority])[:5]
        return AiAnalysisResponse(
            domain=domain,
            range=rng,
            available=True,
            executive_summary=summary,
            key_findings=findings[:5],
            opportunities=opportunities[:5],
            risks=risks[:5],
            recommended_actions=actions,
            generated_at=datetime.now(timezone.utc).isoformat(),
            model=_ENGINE,
        )

    @staticmethod
    def _empty(domain, rng, note) -> AiAnalysisResponse:
        return AiAnalysisResponse(
            domain=domain, range=rng, available=False, note=f"Insufficient data — {note}",
        )
