"""add staff_permissions to users

Revision ID: aebc5b3d052a
Revises: '441126366b9a'
Create Date: 2026-08-09 13:19:34.865150

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebc5b3d052a'
down_revision: Union[str, None] = '441126366b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_permissions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_permissions')
    # ### end Alembic commands ###
