"""Add scheme_enrollments table

Revision ID: d4df4123e0da
Revises: '2089c0255dd2'
Create Date: 2026-07-29 02:05:53.190515

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4df4123e0da'
down_revision: Union[str, None] = '2089c0255dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_enrollments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('enrollment_number', sa.String(length=30), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'enrollment_number', name='uq_enrollments_tenant_number')
    )
    op.create_index(op.f('ix_scheme_enrollments_customer_id'), 'scheme_enrollments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_scheme_enrollments_scheme_id'), 'scheme_enrollments', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_enrollments_status'), 'scheme_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_scheme_enrollments_tenant_id'), 'scheme_enrollments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_enrollments_tenant_id'), table_name='scheme_enrollments')
    op.drop_index(op.f('ix_scheme_enrollments_status'), table_name='scheme_enrollments')
    op.drop_index(op.f('ix_scheme_enrollments_scheme_id'), table_name='scheme_enrollments')
    op.drop_index(op.f('ix_scheme_enrollments_customer_id'), table_name='scheme_enrollments')
    op.drop_table('scheme_enrollments')
    # ### end Alembic commands ###
