"""notification campaigns, platform settings, integrations

Revision ID: aaf86b2870d4
Revises: 'aebc5b3d052a'
Create Date: 2026-08-09 14:35:22.179913

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf86b2870d4'
down_revision: Union[str, None] = 'aebc5b3d052a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_campaigns',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_campaigns_tenant_id'), 'notification_campaigns', ['tenant_id'], unique=False)
    op.create_table('platform_integrations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_integrations_provider'), 'platform_integrations', ['provider'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('default_timezone', sa.String(length=50), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('feature_flags', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('campaign_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_notifications_campaign_id'), 'notifications', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'notification_campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_campaign_id'), table_name='notifications')
    op.drop_column('notifications', 'campaign_id')
    op.drop_table('webhooks')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_platform_integrations_provider'), table_name='platform_integrations')
    op.drop_table('platform_integrations')
    op.drop_index(op.f('ix_notification_campaigns_tenant_id'), table_name='notification_campaigns')
    op.drop_table('notification_campaigns')
    # ### end Alembic commands ###
