"""integration credential storage and platform branding

Revision ID: 9b75ac483d2f
Revises: 'aaf86b2870d4'
Create Date: 2026-08-09 16:33:50.248370

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b75ac483d2f'
down_revision: Union[str, None] = 'aaf86b2870d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_integrations', sa.Column('config_encrypted', sa.Text(), nullable=True))
    op.add_column('platform_settings', sa.Column('logo_url', sa.String(length=1000), nullable=True))
    op.add_column('platform_settings', sa.Column('favicon_url', sa.String(length=1000), nullable=True))
    op.add_column('platform_settings', sa.Column('brand_color_primary', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('brand_color_secondary', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('login_tagline', sa.String(length=255), nullable=True))
    op.add_column('platform_settings', sa.Column('email_from_name', sa.String(length=100), nullable=True))
    op.add_column('platform_settings', sa.Column('custom_domain', sa.String(length=255), nullable=True))
    op.add_column('platform_settings', sa.Column('custom_domain_status', sa.String(length=20), nullable=False, server_default='not_configured'))
    op.alter_column('platform_settings', 'custom_domain_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'custom_domain_status')
    op.drop_column('platform_settings', 'custom_domain')
    op.drop_column('platform_settings', 'email_from_name')
    op.drop_column('platform_settings', 'login_tagline')
    op.drop_column('platform_settings', 'brand_color_secondary')
    op.drop_column('platform_settings', 'brand_color_primary')
    op.drop_column('platform_settings', 'favicon_url')
    op.drop_column('platform_settings', 'logo_url')
    op.drop_column('platform_integrations', 'config_encrypted')
    # ### end Alembic commands ###
