"""add catalogue designs table

Revision ID: f549adae52b4
Revises: 'b6e59f03fbcf'
Create Date: 2026-08-03 18:37:03.123502

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f549adae52b4'
down_revision: Union[str, None] = 'b6e59f03fbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_designs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('source_design_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('canvas_json', sa.Text(), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_design_id'], ['catalogue_designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_designs_product_id'), 'catalogue_designs', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalogue_designs_source_design_id'), 'catalogue_designs', ['source_design_id'], unique=False)
    op.create_index(op.f('ix_catalogue_designs_tenant_id'), 'catalogue_designs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_designs_tenant_id'), table_name='catalogue_designs')
    op.drop_index(op.f('ix_catalogue_designs_source_design_id'), table_name='catalogue_designs')
    op.drop_index(op.f('ix_catalogue_designs_product_id'), table_name='catalogue_designs')
    op.drop_table('catalogue_designs')
    # ### end Alembic commands ###
