"""add tenant contact and branding fields

Revision ID: 7a63facd02af
Revises: '3972b3f05726'
Create Date: 2026-08-04 08:37:13.130467

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a63facd02af'
down_revision: Union[str, None] = '3972b3f05726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('brand_color', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_tenants_contact_email'), 'tenants', ['contact_email'], unique=True)
    op.create_index(op.f('ix_tenants_contact_phone'), 'tenants', ['contact_phone'], unique=True)
    op.create_index(op.f('ix_tenants_gst_number'), 'tenants', ['gst_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_gst_number'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_contact_phone'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_contact_email'), table_name='tenants')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'brand_color')
    op.drop_column('tenants', 'gst_number')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    # ### end Alembic commands ###
