"""Add gold_rates table

Revision ID: 1ca8288f4efe
Revises: '55abda171702'
Create Date: 2026-07-29 00:30:44.184413

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8288f4efe'
down_revision: Union[str, None] = '55abda171702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_rates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('rate_24k', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'effective_date', name='uq_gold_rates_tenant_effective_date')
    )
    op.create_index(op.f('ix_gold_rates_effective_date'), 'gold_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_gold_rates_tenant_id'), 'gold_rates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_rates_tenant_id'), table_name='gold_rates')
    op.drop_index(op.f('ix_gold_rates_effective_date'), table_name='gold_rates')
    op.drop_table('gold_rates')
    # ### end Alembic commands ###
