"""Add passbook_entries table

Revision ID: 9c53a2c83b2d
Revises: 'd4df4123e0da'
Create Date: 2026-07-29 02:30:03.148187

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c53a2c83b2d'
down_revision: Union[str, None] = 'd4df4123e0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passbook_entries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('enrollment_id', sa.String(length=50), nullable=False),
    sa.Column('entry_number', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('gold_rate', sa.Float(), nullable=False),
    sa.Column('gold_weight', sa.Float(), nullable=False),
    sa.Column('running_installment_count', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['scheme_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'entry_number', name='uq_passbook_enrollment_entry_number')
    )
    op.create_index(op.f('ix_passbook_entries_enrollment_id'), 'passbook_entries', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_passbook_entries_tenant_id'), 'passbook_entries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passbook_entries_tenant_id'), table_name='passbook_entries')
    op.drop_index(op.f('ix_passbook_entries_enrollment_id'), table_name='passbook_entries')
    op.drop_table('passbook_entries')
    # ### end Alembic commands ###
