"""add product commercial fields and image shot type

Revision ID: 3972b3f05726
Revises: 'f549adae52b4'
Create Date: 2026-08-04 00:16:14.419027

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3972b3f05726'
down_revision: Union[str, None] = 'f549adae52b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('shot_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_product_images_shot_type'), 'product_images', ['shot_type'], unique=False)
    op.add_column('products', sa.Column('purity', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('weight_grams', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    op.drop_column('products', 'weight_grams')
    op.drop_column('products', 'price')
    op.drop_column('products', 'purity')
    op.drop_index(op.f('ix_product_images_shot_type'), table_name='product_images')
    op.drop_column('product_images', 'shot_type')
    # ### end Alembic commands ###
